# Generated by Django 4.2.7 on 2025-12-09 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0003_experiment_automl_settings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('visibility', models.CharField(choices=[('public', 'Публичная'), ('unlisted', 'По ссылке'), ('private', 'Приватная')], default='public', max_length=20, verbose_name='Видимость')),
                ('tags', models.CharField(help_text='Через запятую: классификация, медицина, точность>90%', max_length=500, verbose_name='Теги')),
                ('use_cases', models.TextField(blank=True, verbose_name='Примеры использования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('views_count', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('downloads_count', models.IntegerField(default=0, verbose_name='Скачивания')),
                ('forks_count', models.IntegerField(default=0, verbose_name='Форки')),
                ('likes_count', models.IntegerField(default=0, verbose_name='Лайки')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемая')),
                ('featured_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата рекомендации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_models', to=settings.AUTH_USER_MODEL)),
                ('original_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_model', to='datasets.mlmodel')),
            ],
            options={
                'verbose_name': 'Публичная модель',
                'verbose_name_plural': 'Публичные модели',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('visibility', models.CharField(choices=[('public', 'Публичный'), ('unlisted', 'По ссылке'), ('private', 'Приватный')], default='public', max_length=20, verbose_name='Видимость')),
                ('tags', models.CharField(max_length=500, verbose_name='Теги')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('views_count', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('downloads_count', models.IntegerField(default=0, verbose_name='Скачивания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_datasets', to=settings.AUTH_USER_MODEL)),
                ('original_dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_dataset', to='datasets.dataset')),
            ],
            options={
                'verbose_name': 'Публичный датасет',
                'verbose_name_plural': 'Публичные датасеты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('public_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='collaboration.publicmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelFork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата форка')),
                ('forked_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forked_from', to='datasets.mlmodel')),
                ('original_public_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forks', to='collaboration.publicmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_forks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Форк модели',
                'verbose_name_plural': 'Форки моделей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Отредактирован')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='collaboration.modelcomment')),
                ('public_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='collaboration.publicmodel')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='publicmodel',
            index=models.Index(fields=['-created_at'], name='collaborati_created_f7230d_idx'),
        ),
        migrations.AddIndex(
            model_name='publicmodel',
            index=models.Index(fields=['-likes_count'], name='collaborati_likes_c_b9c0d6_idx'),
        ),
        migrations.AddIndex(
            model_name='publicmodel',
            index=models.Index(fields=['-views_count'], name='collaborati_views_c_02e40d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='modellike',
            unique_together={('public_model', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='modelfork',
            unique_together={('original_public_model', 'user')},
        ),
    ]
